### ISSUE TITLE
Exit 128. stderr: fatal: unable to access '<giturl> <folder name>': The requested URL returned error: 400

### ISSUE THREAD

**Issue by karneaud** [brianchung808/git-clone#4]
When trying to run the git clone command in atom I get the above error. should I use a different syntax for creating custom folder names?

**Comment by brianchung808** [comment]
There isn't support for custom folders in the `<url> <folder>` format.

Looking at https://github.com/brianchung808/git-clone/blob/master/lib/git-clone.coffee#L34, we're taking everything inputted and using that to parse out the repo name at https://github.com/brianchung808/git-clone/blob/master/lib/git-clone.coffee#L81. 

It'd be a nice feature to add a custom folder name/path. Perhaps a secondary prompt after the git url?

**Comment by karneaud** [comment]
@brianchung808 a secondary prompt? naw man. if options can be either included in the command to read from a .json it would be nice :-)

**Comment by brianchung808** [comment]
@karneaud hah yeah secondary prompt is less than ideal. 

What would that options json specify?

**Comment by karneaud** [comment]
@brianchung808 what ever additional options that can be supplied to `git clone`
