### ISSUE TITLE
Feature Suggestion - allow duplicate git clones

### ISSUE THREAD

**Issue by cliffordfajardo** [brianchung808/git-clone#6]
Normally when you download a file/directory that has the same name of another inside a directory, OSX renames the duplicate. Would it be possible to do something similar with Git clone? 

Example:
https://github.com/brianchung808/git-clone/issues/new# `Desktop/myGitProject` , then I download another copy from Github to the same folder, OSX renames the new duplicate like so `Desktop/myGitProject(1)`.

Sometimes when I git clone something it's not always to make actual git changes. Often times,  I just git clone just to mess around or demo  changes to an audience at tech meet ups.

**Comment by brianchung808** [comment]
This would be a nice feature. Shouldn't be too bad, just have to check if the directory already exists and if so attach a timestamp to the end of the target. I'm a bit busy at the moment (and also haven't looked at this project in a loooong time) but I'm open to any contributions!
